import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthSession from "./AuthSession";
import ProtectedPage from "./protectedpage"; // 수정된 파일 경로

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "부산 성지고등학교",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthSession>
          <>
            <div>서버 점검중입니다</div>
            <div>
              db 최대 연결 초과로 인한 문제를 해결하고있습니다
              <br />
              version 1.0.2 beta
              <br />
              2/24
            </div>
          </>
        </AuthSession>
      </body>
    </html>
  );
}
