import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthSession from "./AuthSession";
import ProtectedPage from "./protectedpage"; // 수정된 파일 경로

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "부산 성지고등학교",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthSession>
          <ProtectedPage children={children} />
        </AuthSession>
      </body>
    </html>
  );
}
